# fly.toml app configuration file generated for docker-nginx-1-aged-dew-2083 on 2024-02-13T18:48:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-nginx-1-aged-dew-2083'
primary_region = 'nrt'

[build]
  image = 'minhee84/blog:0.3.0'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
